### PR TITLE
Fix handler

### PR DESCRIPTION
**Pull request by ElieDeloumeau**

### CODE REVIEW

**Comment by cmacrae** [comment]
Ummm... not sure if you perhaps opened this by mistake or something?
This doesn't fix anything. It's a change to the name of a handler, which is purely cosmetic (could be named whatever you want). Not to mention, even if it were a legitimate suggestion, the spelling is now incorrect.

See SickRage's official site and GitHub repo/account: it's spelled 'SickRage' not 'Sickrage'.

Closing this.

**Comment by ElieDeloumeau** [comment]
But your role doesn't work with ansible 2.3... I can commit with uppercase R if you want but the notify and the service must have the same case.

**Comment by cmacrae** [comment]
Ah! Okay, I see exactly what you mean now. It's usually good practice/courtesy to include a description with PRs explaining your changes ;)

I'll update the handler's name to use the correct spelling.

**Comment by ElieDeloumeau** [comment]
Yes i've made this PR too quickly x)

**Comment by cmacrae** [comment]
Haha, no worries - thanks for picking this up 👍  I haven't touched this role in a while as I started using Sonarr

**Pull request closed without merging**
